package gregtech.common.items;

import gregtech.api.items.materialitem.MaterialMetaItem;
import gregtech.api.unification.ore.OrePrefix;

public class MetaMoreAutogeneratedResources extends MaterialMetaItem {
	
	public MetaMoreAutogeneratedResources() {
		super(OrePrefix.cluster, OrePrefix.clump, OrePrefix.shard, OrePrefix.crystal, OrePrefix.dustDirty);
	}

}
