package gregtech.common.items;

import gregtech.api.items.materialitem.MaterialMetaItem;
import gregtech.api.unification.ore.OrePrefix;

public class MetaAutogeneratedParts extends MaterialMetaItem {
	
	public MetaAutogeneratedParts() {
		super(OrePrefix.screw, OrePrefix.ring, OrePrefix.foil, OrePrefix.plate, OrePrefix.stick, OrePrefix.lens,
			  OrePrefix.turbineBlade, OrePrefix.gear, OrePrefix.wireFine, OrePrefix.gearSmall, OrePrefix.rotor, 
			  OrePrefix.spring);
	}

}
